spring.application.name=finance-dashboard

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/financedb
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=${password}

# JPA Configuration

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT Configuration
jwt.secret=finance_dashboard_jwt_secret_key_this_must_be_at_least_64_characters_long_for_hs512_algorithm
jwt.expiration=86400000
